import type { NextPage } from "next";
import Head from "next/head";
import Header from "../components/Header";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Salman&apos;s Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <main className="mx-auto flex flex-col items-center justify-center min-h-screen p-4">
        <h1 className="text-red-500 font-bold text-6xl">Hello!</h1>
      </main>

      <footer></footer>
    </>
  );
};

export default Home;
