import Head from "next/head";
import type { NextPage } from "next";

import Header from "../components/Header";
import Landing from "../components/Landing";
import About from "../components/About";
import Experience from "../components/Experience";

const Home: NextPage = () => {
  return (
    <div className="bg-[#022525] text-white h-screen snap-y snap-mandatory overflow-scroll z-0">
      <Head>
        <title>Salman&apos;s Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <main>
        <section id="landing" className="snap-center">
          <Landing />
        </section>
        <section id="about" className="snap-center">
          <About />
        </section>
        <section id="experience" className="snap-center">
          <Experience />
        </section>
      </main>

      <footer></footer>
    </div>
  );
};

export default Home;
